name: jupyterlite-p5-kernel
channels:
- conda-forge
dependencies:
- build
- pip
- python=3.11
- mamba
- pydata-sphinx-theme
- myst-parser
- ipywidgets>=8.1,<9
- jupyterlab>=4.5.0,<5
- nodejs=22
- jupyterlite-core>=0.7.0,<0.8
- jupyterlite-sphinx